set_humidity:
  name: Set humidity
  description: Set the target humidity of WeMo humidifier devices.
  target:
    entity:
      integration: wemo
      domain: fan
  fields:
    target_humidity:
      name: Target humidity
      description: Target humidity.
      required: true
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: '%'

reset_filter_life:
  name: Reset filter life
  description: Reset the WeMo Humidifier's filter life to 100%.
  target:
    entity:
      integration: wemo
      domain: fan

crockpot_update_settings:
  # Description of the service
  description: Updates crockpot settings
  target:
    entity:
      integration: wemo
      domain: switch
  # Different fields that your service accepts
  fields:
    # Key of the field
    mode:
      description: Cooking mode
      example: '50'
    time:
      description: Cooking time
      example: '300'
