set_humidity:
  description: Set the target humidity of WeMo humidifier devices.
  fields:
    entity_id:
      description: Names of the WeMo humidifier entities (1 or more entity_ids are required).
      example: "fan.wemo_humidifier"
    target_humidity:
      description: Target humidity. This is a float value between 0 and 100, but will be mapped to the humidity levels that WeMo humidifiers support (45, 50, 55, 60, and 100/Max) by rounding the value down to the nearest supported value.
      example: 56.5

reset_filter_life:
  description: Reset the WeMo Humidifier's filter life to 100%.
  fields:
    entity_id:
      description: Names of the WeMo humidifier entities (1 or more entity_ids are required).
      example: "fan.wemo_humidifier"

crockpot_update_settings:
  # Description of the service
  description: Updates crockpot settings
  # Different fields that your service accepts
  fields:
    # Key of the field
    entity_id:
      # Description of the field
      description: Name(s) of the entities to set
      # Example value that can be passed for this field
      example: 'switch.kitchen_slow_cooker'
    mode:
      description: Cooking mode
      example: '50'
    time:
      description: Cooking time
      example: '300'